### ISSUE TITLE
Hint optimizations - Reinforcing chances of hint usefulness

### ISSUE THREAD

**Issue by wizardwhosaysni** [Dinopony/randstalker#11]
Hey Dino,

By now I must have played around a dozen seeds in the past month, and I just want to play it again and again. :D
I'd like to share my thoughts from my experience so far, and eventually open the discussion for possible optimizations regarding hints.

A few factual observations for a start :

1. Late-game random exploration when remaining items have no hints
With default options, a considerable proportion of seeds (~50% ?) do not provide any hint for one or several late-game critical items.
This results in a somewhat frustrating random research through all unvisited, non-barren regions, relying on luck only.
Sometimes the research unluckily reaches almost 100% completion and a more than 3-hour-long game, feeling not as enjoyable as seeds with more useful hints.

2. Hints unreachable before getting related item
Sometimes a hint can be about an item which is required to reach the hint itself : the hint is guaranteed to be useless.

More of a personal feeling :
I agree that not all seeds should provide enough hints to resolve the whole critical path.
It would become too easy and less exciting if all we have to do is go for the hints and apply them. 
A seed should always have an amount of uncertainty to bring good fun and moments of hesitation between several region candidates.
But I believe it would be more enjoyable if these cases of "100%-inducing seeds" were a bit more marginal, by ensuring that most hints can be useful.
I think that only a few small functional changes could already have quite a positive impact on this "enjoyable seed"/"frustrating seed" ratio.

Functional suggestions :

1. It might be possible to have a better control of hint item distribution by considering a hint's region, to make sure the hinted item isn't required to reach the hint.
This change alone should already have great benefits in terms of general hint efficiency.

2. The Oracle Stone should apply the same rule to ensure that it can be reached without it's hinted item.
  
At first I had further ideas but I think this kind of optimization alone should already be experimented first before judging if more tuning is needed or not. It could well be enough to avoid any kind of useless hint.

I tried to implement it tonight and the results don't seem too bad, from what I can see in generated logs.
Here's the branch : 
https://github.com/wizardwhosaysni/randstalker/commits/hint_optimizations 

I'll play a few seeds coming from this branch in the next days and I'll let you know if the frustration of useless hints is gone away. :D 
But please tell me your thoughts and don't hesitate to tell me if thee's anything wrong in my implementation.
  
Just notes below, written along my code reading and reflections.
```   
Hintable items

Putting aside special case of Red/Purple Jewels :
Combination of KNC sign hint + lithograph works great, and even sometimes motivates to rush through mountainous area with Gola's Eye ASAP. 

8 guaranteed critical items
  Safety Pass
  Sunstone/Key (grouping them from a functional point of view, but no plan to manage them specifically, in my opinion the difference wouldn't be that significant to deserve such a change)
  Axe Magic
  Gola's Eye
  Snow Spikes
  Gola's Nail
  Gola's Fang
  Gola's Horn

6 potentially critical items
  Buyer Card
  Einstein Whistle
  Armlet
  Garlic
  Idol Stone
  Casino Ticket

4 dispensable items
  Thunder Sword
  Healing Boots
  Venus Stone
  Statue of Jypta
  
24 macro-regions evaluated as barren or containing a pleasant surprise : stricly needed items only.

The region hint/item hint ratio is around 4/3 in the générated hint pool, so that explains why we get region hints most of the time, which is a good thing : region hints rely on strictly needed items, while item hints rely on "important items" (notable items, but not all of them are strictly needed).


Hint slots 

Putting aside Fortune Teller hint :
Works great with Gola items only, no reason to change it.

13 default hints

1 mobile hint
  Oracle Stone
  
3 early-game region hints
  Waterfall Shrine crossroad sign
  Swamp Shrine crossroad sign
  Tibor crossroad sign
2 mid-game region hints (post-Safety Pass)
 Items to exclude : Safety Pass
  Mir Tower sector crossroad sign
  Mir Tower exterior sign
7 late-game region hints (Post Sunstone/key)
 Items to exclude : Safety Pass, Key, Sunstone
  Verla crossroad sign
  Destel crossroad sign
  Lake Shrine / Mountainous crossroad sign
  Greenmaze / Mountainous crossroad sign
  Center of Greenmaze sign
  Greenmaze / Massan shortcut tunnel sign
  Volcano sign

7 optional hints

3 early-game
  Thieves' Hideout entrance sign
  Thieves' Hideout second room sign
  Thieves' Hideout boss path sign
4 mid-game
 Items to exclude : Safety Pass
  Mir Tower sign before bridge room
  Mir Tower bridge room sign
  Mir Tower library sign
  Mir Tower sign before library

```

**Comment by Dinopony** [comment]
You raise fair points on this issue, and changes from your PR seems like a good start to see how it goes.
This is something I've been considering to do for quite some time, but never actually thought about how to do it properly.

**Comment by wizardwhosaysni** [comment]
Tracking first related PR : https://github.com/Dinopony/randstalker/pull/12

As discussed, changes applied to Oracle Stone and item-driven hints, but not on region-driven hints.

**Comment by wizardwhosaysni** [comment]
Just keeping track of another PR, specifically for optionnally required key items : https://github.com/Dinopony/randstalker/pull/13

Now mostly needing to play a lot and see how it feels.

**Comment by Dinopony** [comment]
Closing this since the first pass was successfull in fixing the original issue.
