### ISSUE TITLE
Fix misplaced / laggy / buggy Foxy placements

### ISSUE THREAD

**Issue by Dinopony** [Dinopony/randstalker#30]
Some Foxies cause excessive lags and / or are slightly misplaced and should be fixed.
Here is the list of known problematic Foxies:

- Path to Lake Shrine (half in ground) [fixed]
- First room of Mir Tower teleporter Maze (misplaced in a weird way) [fixed]
- King Nole's Labyrinth spiral room (**very laggy**) [fixed in 03ad95f9899a8f301885fe0fb568283af90f9d84]
- Lava room in Marley sector of Verla Mines (laggy with lizards) [fixed in ddfc38227ed197b9d9a8e4fcdff4a883d8f0aea0]
- Close to Mountainous Area's waterfall (buggy palette with specters) [fixed in da2ccd3d62f663abf35382d455c3256848239688]
- King Nole's Cave teleporter to Kazalt (cannot be found in map) [fixed in 6841372b1a3ad030e2c129f1bcfa119ea2270eca]

**Comment by wizardwhosaysni** [comment]
Reported by Sagaz today, this one cannot be found :
"Foxy (in King Nole's Cave teleporter to Kazalt)": "What you are looking for is not in King Nole's palace."

**Comment by Dinopony** [comment]
Tiles overlapping when spectres shoot fireballs
https://clips.twitch.tv/WealthyAmorphousBaguetteGOWSkull-kA5dLAjwnWMtEQON

**Comment by Dinopony** [comment]
All fixed and tested
